### ISSUE TITLE
Failed to download yue: Release not found: 404

### ISSUE THREAD

**Issue by LoganDark** [yue/node-gui#22]
Shell

```
0 LoganDark ~/gui-test npm i --save gui

> gui@0.5.0 postinstall /Users/LoganDark/gui-test/node_modules/gui
> node install.js

Failed to download yue: Release not found: 404
npm WARN gui-test@0.0.1 No description
npm WARN gui-test@0.0.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gui@0.5.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gui@0.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/LoganDark/.npm/_logs/2018-07-09T08_44_08_065Z-debug.log
```

`2018-07-09T08_44_08_065Z-debug.log`
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/LoganDark/.nvm/versions/node/v10.1.0/bin/node',
1 verbose cli   '/Users/LoganDark/.nvm/versions/node/v10.1.0/bin/npm',
1 verbose cli   'i',
1 verbose cli   '--save',
1 verbose cli   'gui' ]
2 info using npm@6.1.0
3 info using node@v10.1.0
4 verbose npm-session e3867644b8752989
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/gui 14ms (from cache)
8 silly pacote tag manifest for gui@latest fetched in 33ms
9 timing stage:loadCurrentTree Completed in 218ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 21ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule gui@0.5.0 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/download-yue 9ms (from cache)
18 silly pacote range manifest for download-yue@2.x fetched in 11ms
19 silly resolveWithNewModule download-yue@2.0.0 checking installable status
20 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 25ms
21 timing stage:loadIdealTree Completed in 51ms
22 silly currentTree gui-test@0.0.1
22 silly currentTree ├── arrify@1.0.1
22 silly currentTree ├── buffer-from@1.1.0
22 silly currentTree ├── diff@3.5.0
22 silly currentTree ├── make-error@1.3.4
22 silly currentTree ├── minimist@1.2.0
22 silly currentTree ├─┬ mkdirp@0.5.1
22 silly currentTree │ └── minimist@0.0.8
22 silly currentTree ├── source-map-support@0.5.6
22 silly currentTree ├── source-map@0.6.1
22 silly currentTree ├── ts-node@7.0.0
22 silly currentTree ├── typescript@2.9.2
22 silly currentTree └── yn@2.0.0
23 silly idealTree gui-test@0.0.1
23 silly idealTree ├── arrify@1.0.1
23 silly idealTree ├── buffer-from@1.1.0
23 silly idealTree ├── diff@3.5.0
23 silly idealTree ├── download-yue@2.0.0
23 silly idealTree ├── gui@0.5.0
23 silly idealTree ├── make-error@1.3.4
23 silly idealTree ├── minimist@1.2.0
23 silly idealTree ├─┬ mkdirp@0.5.1
23 silly idealTree │ └── minimist@0.0.8
23 silly idealTree ├── source-map-support@0.5.6
23 silly idealTree ├── source-map@0.6.1
23 silly idealTree ├── ts-node@7.0.0
23 silly idealTree ├── typescript@2.9.2
23 silly idealTree └── yn@2.0.0
24 silly install generateActionsToTake
25 timing stage:generateActionsToTake Completed in 5ms
26 silly diffTrees action count 2
27 silly diffTrees add download-yue@2.0.0
28 silly diffTrees add gui@0.5.0
29 silly decomposeActions action count 16
30 silly decomposeActions fetch download-yue@2.0.0
31 silly decomposeActions extract download-yue@2.0.0
32 silly decomposeActions preinstall download-yue@2.0.0
33 silly decomposeActions build download-yue@2.0.0
34 silly decomposeActions install download-yue@2.0.0
35 silly decomposeActions postinstall download-yue@2.0.0
36 silly decomposeActions finalize download-yue@2.0.0
37 silly decomposeActions refresh-package-json download-yue@2.0.0
38 silly decomposeActions fetch gui@0.5.0
39 silly decomposeActions extract gui@0.5.0
40 silly decomposeActions preinstall gui@0.5.0
41 silly decomposeActions build gui@0.5.0
42 silly decomposeActions install gui@0.5.0
43 silly decomposeActions postinstall gui@0.5.0
44 silly decomposeActions finalize gui@0.5.0
45 silly decomposeActions refresh-package-json gui@0.5.0
46 silly install executeActions
47 silly doSerial global-install 16
48 verbose correctMkdir /Users/LoganDark/.npm/_locks correctMkdir not in flight; initializing
49 timing audit compress Completed in 3ms
50 info audit Submitting payload of 1217bytes
51 verbose lock using /Users/LoganDark/.npm/_locks/staging-aa01978564c21233.lock for /Users/LoganDark/gui-test/node_modules/.staging
52 silly doParallel extract 2
53 silly extract download-yue@2.0.0
54 silly extract gui@0.5.0
55 timing audit submit Completed in 420ms
56 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 429ms
57 timing audit body Completed in 10ms
58 timing action:extract Completed in 407ms
59 silly doReverseSerial unbuild 16
60 silly doSerial remove 16
61 silly doSerial move 16
62 silly doSerial finalize 16
63 silly finalize /Users/LoganDark/gui-test/node_modules/download-yue
64 silly finalize /Users/LoganDark/gui-test/node_modules/gui
65 timing action:finalize Completed in 5ms
66 silly doParallel refresh-package-json 2
67 silly refresh-package-json /Users/LoganDark/gui-test/node_modules/download-yue
68 silly refresh-package-json /Users/LoganDark/gui-test/node_modules/gui
69 timing action:refresh-package-json Completed in 10ms
70 silly doParallel preinstall 2
71 silly preinstall download-yue@2.0.0
72 info lifecycle download-yue@2.0.0~preinstall: download-yue@2.0.0
73 silly preinstall gui@0.5.0
74 info lifecycle gui@0.5.0~preinstall: gui@0.5.0
75 timing action:preinstall Completed in 2ms
76 silly doSerial build 16
77 silly build download-yue@2.0.0
78 info linkStuff download-yue@2.0.0
79 silly linkStuff download-yue@2.0.0 has /Users/LoganDark/gui-test/node_modules as its parent node_modules
80 verbose linkBins [ { 'download-yue': 'download-yue.js' },
80 verbose linkBins   '/Users/LoganDark/gui-test/node_modules/.bin',
80 verbose linkBins   false ]
81 silly build gui@0.5.0
82 info linkStuff gui@0.5.0
83 silly linkStuff gui@0.5.0 has /Users/LoganDark/gui-test/node_modules as its parent node_modules
84 timing action:build Completed in 5ms
85 silly doSerial global-link 16
86 silly doParallel update-linked 0
87 silly doSerial install 16
88 silly install download-yue@2.0.0
89 info lifecycle download-yue@2.0.0~install: download-yue@2.0.0
90 silly install gui@0.5.0
91 info lifecycle gui@0.5.0~install: gui@0.5.0
92 timing action:install Completed in 0ms
93 silly doSerial postinstall 16
94 silly postinstall download-yue@2.0.0
95 info lifecycle download-yue@2.0.0~postinstall: download-yue@2.0.0
96 silly postinstall gui@0.5.0
97 info lifecycle gui@0.5.0~postinstall: gui@0.5.0
98 verbose lifecycle gui@0.5.0~postinstall: unsafe-perm in lifecycle true
99 verbose lifecycle gui@0.5.0~postinstall: PATH: /Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/LoganDark/gui-test/node_modules/gui/node_modules/.bin:/Users/LoganDark/gui-test/node_modules/.bin:/Users/LoganDark/google-cloud-sdk/bin:/Users/LoganDark/.nvm/versions/node/v10.1.0/bin:/Users/LoganDark/.cargo/bin:/etc/pypy/bin:/Users/LoganDark/go/bin:/usr/local/opt/unzip/bin:/opt/metasploit-framework/bin:/Users/LoganDark/.nvm/versions/node/v10.1.0/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Library/TeX/texbin
100 verbose lifecycle gui@0.5.0~postinstall: CWD: /Users/LoganDark/gui-test/node_modules/gui
101 silly lifecycle gui@0.5.0~postinstall: Args: [ '-c', 'node install.js' ]
102 silly lifecycle gui@0.5.0~postinstall: Returned: code: 1  signal: null
103 info lifecycle gui@0.5.0~postinstall: Failed to exec postinstall script
104 timing action:postinstall Completed in 564ms
105 verbose unlock done using /Users/LoganDark/.npm/_locks/staging-aa01978564c21233.lock for /Users/LoganDark/gui-test/node_modules/.staging
106 timing stage:rollbackFailedOptional Completed in 4ms
107 timing stage:runTopLevelLifecycles Completed in 1340ms
108 silly saveTree gui-test@0.0.1
108 silly saveTree ├─┬ gui@0.5.0
108 silly saveTree │ └── download-yue@2.0.0
108 silly saveTree ├─┬ ts-node@7.0.0
108 silly saveTree │ ├── arrify@1.0.1
108 silly saveTree │ ├── buffer-from@1.1.0
108 silly saveTree │ ├── diff@3.5.0
108 silly saveTree │ ├── make-error@1.3.4
108 silly saveTree │ ├── minimist@1.2.0
108 silly saveTree │ ├─┬ mkdirp@0.5.1
108 silly saveTree │ │ └── minimist@0.0.8
108 silly saveTree │ ├─┬ source-map-support@0.5.6
108 silly saveTree │ │ └── source-map@0.6.1
108 silly saveTree │ └── yn@2.0.0
108 silly saveTree └── typescript@2.9.2
109 warn gui-test@0.0.1 No description
110 warn gui-test@0.0.1 No repository field.
111 verbose stack Error: gui@0.5.0 postinstall: `node install.js`
111 verbose stack Exit status 1
111 verbose stack     at EventEmitter.<anonymous> (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
111 verbose stack     at EventEmitter.emit (events.js:182:13)
111 verbose stack     at ChildProcess.<anonymous> (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
111 verbose stack     at ChildProcess.emit (events.js:182:13)
111 verbose stack     at maybeClose (internal/child_process.js:957:16)
111 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
112 verbose pkgid gui@0.5.0
113 verbose cwd /Users/LoganDark/gui-test
114 verbose Darwin 18.0.0
115 verbose argv "/Users/LoganDark/.nvm/versions/node/v10.1.0/bin/node" "/Users/LoganDark/.nvm/versions/node/v10.1.0/bin/npm" "i" "--save" "gui"
116 verbose node v10.1.0
117 verbose npm  v6.1.0
118 error code ELIFECYCLE
119 error errno 1
120 error gui@0.5.0 postinstall: `node install.js`
120 error Exit status 1
121 error Failed at the gui@0.5.0 postinstall script.
121 error This is probably not a problem with npm. There is likely additional logging output above.
122 verbose exit [ 1, true ]
```

System:

```
                -/+:.          LoganDark@base.local
               :++++.          --------------------
              /+++/.           Model: MacBookPro11,5
      .:-::- .+/:-``.::-       OS: Mac OS X 10.14 18A326g x86_64
   .:/++++++/::::/++++++/:`    Kernel: 18.0.0
 .:///////////////////////:`   Uptime: up 1 day, 6 hours, 27 minutes
 ////////////////////////`     Packages: 343
-+++++++++++++++++++++++`      Shell: /bin/bash
/++++++++++++++++++++++/       Resolution: 1440x900
/sssssssssssssssssssssss.      DE: Aqua
:ssssssssssssssssssssssss-     WM: Quartz Compositor
 osssssssssssssssssssssssso/`  WM Theme: Blue
 `syyyyyyyyyyyyyyyyyyyyyyyy+`  Terminal: iTerm2
  `ossssssssssssssssssssss/    CPU: Intel Core i7-4870HQ (8) @ 2.50GHz
    :ooooooooooooooooooo+.     GPU: AMD Radeon R9 M370X, Intel Iris Pro
     `:+oo+/:-..-:/+o+/-       Memory: 3737MB / 16384MB
```

Node, NPM:

```
0 LoganDark ~/gui-test node -v
v10.1.0
0 LoganDark ~/gui-test npm -v
6.1.0
```

**Comment by LoganDark** [comment]
I can download yue manually and use it.
![image](https://user-images.githubusercontent.com/4723091/42441815-eaf6bd44-831d-11e8-9eac-8f14a7ae1df4.png)

**Comment by LoganDark** [comment]
Oh wait, nevermind. Apparently this thing has absolutely no compatibility with any node version other than exactly `8.0.0`. What a joke.

But in related news, Yue works now.

**Comment by aliasgharkarani** [comment]
![Screen Shot 2019-09-07 at 5 17 52 PM](https://user-images.githubusercontent.com/33603201/64474809-78e23880-d193-11e9-92a5-508fa0809f87.png)
Still getting this
